baseURL = 'https://edwintye.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-blog-awesome'

# Definitely not enabling SEO
enableRobotsTXT = false

[author]
    name = 'Edwin Tye'

[markup]
    [markup.highlight]
        noClasses = false

[params]
    defaultColor = 'dark'
    dateFormat = '2006-01-02'
